# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "Bahr"
languages = ["C"]

[variables]
CMAKE_CXX_STANDARD = "23"
CMAKE_C_STANDARD = "23"

# Targets
[target.bahr-cli]
type = "my_executable"
sources = ["src/cli/*.c"]
link-libraries = ["bahr-codegen-llvm"]

[target.bahr-codegen-llvm]
type = "my_library"
sources = ["src/codegen-llvm/*.c"]
link-libraries = ["parser", "LLVM"]

[target.parser]
type = "my_library"
sources = ["src/parser/*.c"]
link-libraries = ["arena", "hashmap"]

[target.arena]
type = "my_library"
sources = ["src/arena/*.c"]

[target.hashmap]
type = "my_library"
sources = ["src/hashmap/*.c"]

[target.utility]
type = "my_interface"
sources = ["src/utility/*.h"]

# Templates
[template.my_executable]
type = "executable"
include-directories = ["src"]
compile-options = ["-Wall", "-Werror", "-Wextra", "-Wpedantic"]
link-libraries = ["utility", "jemalloc"]
link-options = ["-fuse-ld=mold"]

[template.my_library]
type = "static"
include-directories = ["src"]
compile-options = ["-Wall", "-Werror", "-Wextra", "-Wpedantic"]
link-libraries = ["utility", "jemalloc"]
link-options = ["-fuse-ld=mold"]

[template.my_interface]
type = "interface"
include-directories = ["src"]
compile-options = ["-Wall", "-Werror", "-Wextra", "-Wpedantic"]

# Tests
# TODO: add tests
