# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "comp-test3"
languages = ["C"]

# Targets
[target.bin]
type = "my_executable"
sources = ["./src/bin/*.c"]
link-libraries = ["arena", "parser", "codegen"]

[target.codegen]
type = "my_library"
sources = ["./src/codegen/*.c"]
link-libraries = ["LLVM"]

[target.parser]
type = "my_library"
sources = ["./src/parser/*.c"]

[target.arena]
type = "my_library"
sources = ["./src/arena/*.c"]

[target.fxhash]
type = "my_library"
sources = ["./src/fxhash/*.c"]

[target.utility]
type = "my_interface"
sources = ["./src/utility/*.h"]

# Templates
[template.my_executable]
type = "executable"
include-directories = ["src"]
compile-options = ["-Wall", "-Werror", "-Wextra", "-std=c2x"]
link-libraries = ["utility", "mimalloc"]

[template.my_library]
type = "static"
include-directories = ["src"]
compile-options = ["-Wall", "-Werror", "-Wextra", "-std=c2x"]
link-libraries = ["utility", "mimalloc"]

[template.my_interface]
type = "interface"
include-directories = ["src"]
compile-options = ["-Wall", "-Werror", "-Wextra", "-std=c2x"]
link-libraries = ["mimalloc"]

# Tests
# TODO: add tests
